### ISSUE TITLE
"Can't Find VM" instead of create a new one on vcd_vapp_vm

### ISSUE THREAD

**Issue by danielc256** [vmware/ansible-module-vcloud-director#135]
Hello,

I'm facing a issue, I saw a previous post about it but it didn't worked for me.

- name: Create VM on SAT environment
  no_log: False
  vcd_vapp_vm:
    target_vm_name: "{{ item.vm_name }}"
    target_vapp: "{{ vapp }}"
    target_vdc: "{{ vdc }}"
    source_catalog_name: "{{ catalog }}"
    source_template_name: "{{ template_cicd }}"
    state: "present"
  with_items: "{{ cicd_vm }}"

Output:
line 313, in get_vm\n File "/root/.local/lib/python3.6/site-packages/pyvcloud/vcd/vapp.py", line 633, in get_vm\n raise EntityNotFoundException('Can\'t find VM \'%s\'' % vm_name)\npyvcloud.vcd.exceptions.EntityNotFoundException: Can't find VM 'new'\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n

My playbook is configured like this:

- name: vCloudDirectorAnsible
  hosts: localhost
  environment:
    env_user: "user"
    env_password: "Teste123!"
    env_host: "{{ vcloud_host }}"
    env_org: "{{ organization }}"
    env_api_version: 32.0
    env_verify_ssl_certs: false

  roles:
    - simple_role

It should create a new VM instead of find an existing one, why is it not doing that? 

Note: I got perform a few tasks like create a vAPP, catalog, so I can authenticate on vCloud, the problem is this specific module

**Comment by mukultaneja** [comment]
@danielc256 from the playbook I could see you are missing the `source_vm_name` argument. Please try with this argument once and share the whole traceback log which would help to understand what exact error it is throwing. `Can't find VM` exception is coming because the module tries to search first if any VM with the same name is present in the vApp and if it did not get then it tries to create it.  You can verify the arguments from the [wiki page](https://github.com/vmware/ansible-module-vcloud-director/wiki/vCD-vApp-VM)

**Comment by danielc256** [comment]
Hello, you're right

The playbook that resolved my problem:

- name: Create first VM
  vcd_vapp_vm:
    target_vm_name: "{{ item.vm_name }}"
    target_vapp: "{{ vapp_midtier }}"
    source_vdc: "{{ virtual_datacenter }}"
    target_vdc: "{{ virtual_datacenter }}"
    source_catalog_name: "{{ catalog }}"
    source_template_name: "{{ cicd_template }}"
    source_vm_name: "{{ cicd_template }}"
    hostname: "{{ item.hostname }}"
    state: "present"
    power_on: false
  with_items: "{{ cicd_vm }}"
  ignore_errors: yes

**Comment by danielc256** [comment]
Note: It will give a error, it pass if you put a network parameter on it, because of that I put the ignore_errors module to go ahead even with the error, the machine will be created anyway

**Comment by mertyakan** [comment]
Hello, I noticed something. If you add network to vapps, it doesn't give an error when installing a new virtual machine,

The network card you add must be predefined in Vapps, where the virtual machine you created will be included.  @dancamarg0

**Comment by dancamarg0** [comment]
Hi @mertyakan, this will work when you have only 1 NIC, but if you need to add more than one it will give you the same error (As far as I can remember, the last time I tested it was a few months ago)

I also found out at the time the error was occurring due to the template's NIC, if you remove it and let your template without any NIC it will not spill that error.
