### ISSUE TITLE
Adding more than 1 Org Network to a vAPP

### ISSUE THREAD

**Issue by danielc256** [vmware/ansible-module-vcloud-director#136]
I'm facing a problem to add 2 or more networks to a single vapp, see my ansible task:

- name: Create FRONTEND vAPP
  vcd_vapp:
    vapp_name: "{{ vapp_frontend }}"
    vdc: "{{ virtual_datacenter }}"
    network: "{{ item.value }}"
    power_on: False
    state: "present"
  with_dict: "{{ frontend_network }}"

It reads normally, however it adds just the first 1, and at the time to add the second one it just say that the vAPP already exists e don't add, see below a printscreen:

![image](https://user-images.githubusercontent.com/67828229/93714867-5b44fe80-fb5d-11ea-9ee6-1eb2ba3abb2a.png)

And create just the first one, any suggestions to add the 2 networks? It could be another task too, no problem.

**Comment by mukultaneja** [comment]
@danielc256 Please use [vcd_vapp_network](https://github.com/vmware/ansible-module-vcloud-director/wiki/vCD-vApp-Network) module to add networks to a vApp. The module `vcd_vapp` is just to create a new vApp in VCD. At first run you have already created it that is why you are getting this warning while running on second time.

**Comment by danielc256** [comment]
Hello,

I'm using this module because vcd_vapp_network didn't work for me.

Notice that I use OrgVDC Network, and vCloud can just find it when I use vcd_app module

Always when I try to add a OrgVDC Network it doesn't work on vcd_app_network module

**Comment by danielc256** [comment]
Notice that my case is not to create or update a Network, but to add an already existing one.

I tried in several ways, but I just can add through vcd_vapp module, and as you saw on images below it just add 1 and the other it perform the idempotency.

See that on Wiki there is no an example to this situation: https://github.com/vmware/ansible-module-vcloud-director/wiki/vCD-vApp-Network

**Comment by danielc256** [comment]
It would be the equivalent to add like this on GUI:

![image](https://user-images.githubusercontent.com/67828229/93516765-68c27480-f922-11ea-8949-773ccd104246.png)

See that vcd_vapp_network only support work on right option "vAPP Network"

**Comment by mukultaneja** [comment]
@danielc256, as I could see in the `vcd_vapp_network`'s playbook I think you are missing the `network_cidr ` attribute. Please try adding the `network_cidr ` attribute once. You can follow the [wiki ](https://github.com/vmware/ansible-module-vcloud-director/wiki/vCD-vApp-Network)to add new VAPP network

**Comment by mukultaneja** [comment]
@danielc256, are you able to resolve this issue?

**Comment by sgutermann** [comment]
Reads similar or same as my issue. I copied the playbook above and added the cidr to it. No go.

The full traceback is:
Traceback (most recent call last):
  File "/tmp/ansible_vcd_vapp_network_payload_ye3d232c/ansible_vcd_vapp_network_payload.zip/ansible/modules/vcd_vapp_network.py", line 226, in add_network
  File "/tmp/ansible_vcd_vapp_network_payload_ye3d232c/ansible_vcd_vapp_network_payload.zip/ansible/modules/vcd_vapp_network.py", line 198, in get_network
pyvcloud.vcd.exceptions.EntityNotFoundException: Can't find the specified vApp network

I double and tripple checked and the network exists with that exact name. If I attach that network as first network with vcd_vapp it gets found and used.

**Comment by danielc256** [comment]
I'm not able to test with this version of Python now, but I will give the output as soon as possible.

Meanwhile, I got another Python's module to use if anyone have this same problem.

https://vmware.github.io/vcd-cli/

My code for that:

- name: Log on vCloud API through vcd-cli
  shell: "vcd login {{ vcd_host }} {{ vcd_organization }} {{ vcd_user }} --password {{ vcd_password }} -iw --version {{ api_version }}"

############## FRONTEND vAPP ##############

- name: Create FRONTEND vAPP with Service network
  shell: "vcd vapp create -n {{ frontend_network }} {{ vapp_frontend }}"

- name: Add OAM Network to FRONTEND vAPP
  shell: "vcd vapp connect {{ vapp_frontend }} {{ oam_frontend_network }}"

**Comment by sgutermann** [comment]
@danielc256 thank you. That is just a CLI Interface to the same API which the Ansible Modules here are using as well. 

@mukultaneja just needs to fix the module so it works as it did in the past and all is well.

:)

**Comment by mukultaneja** [comment]
@danielc256 @sgutermann, do you want to attach a new vApp network or an Org VDC network to a vApp?

**Comment by sgutermann** [comment]
@mukultaneja another already existing Org VDC Net.

**Comment by mukultaneja** [comment]
@sgutermann @danielc256, I have added two operations `add_org_network` and `delete_org_network` to an existing vApp module. Please take a look at my latest commit and try once.

**Comment by mukultaneja** [comment]
I have updated the [wiki](https://github.com/vmware/ansible-module-vcloud-director/wiki/vCD-vApp) as well with new operations.

**Comment by sgutermann** [comment]
> 
> 
> I have updated the [wiki](https://github.com/vmware/ansible-module-vcloud-director/wiki/vCD-vApp) as well with new operations.

Thank you, hoever the module documentation does not seem quite right.

ansible-doc -t module vcd_vapp
ERROR! module vcd_vapp missing documentation (or could not parse documentation): while scanning a simple key
  in "<unicode string>", line 118, column 5
could not find expected ':'
  in "<unicode string>", line 119, column 20

**Comment by sgutermann** [comment]
@mukultaneja just tested it. And the part for adding the VDC Org Network to the vAPP works. 

BUT

Adding it after that to a VM in the vAPP is now suddenly asking for an adapter type. 

vcd_vapp_vm_nic

does not have that parameter.

##### playbook part ####

      - name: VMWARE_CLOUDDIRECTOR_CREATE_VM | Create vapp vm secondary nic
        vcd_vapp_vm_nic:
          vm_name: "{{ inventory_hostname }}"
          vapp: "{{ inventory_hostname }}"
          vdc: "{{ vdc }}"
          network: "{{ secondnetwork }}"
          ip_allocation_mode: "MANUAL"
          ip_address: "{{ secondip }}"
          state: "present"

### end ###

### new error ###

TASK [VMWARE_CLOUDDIRECTOR_CREATE_VM | Create vapp vm secondary nic] **********************************************************************************************************************************************
task path: /home/steffen/Work/ansible-optica/tools/vmware_clouddirector_create_vm.yml:61
The full traceback is:
Traceback (most recent call last):
  File "/tmp/ansible_vcd_vapp_vm_nic_payload_i55hukqe/ansible_vcd_vapp_vm_nic_payload.zip/ansible/modules/vcd_vapp_vm_nic.py", line 285, in main
  File "/tmp/ansible_vcd_vapp_vm_nic_payload_i55hukqe/ansible_vcd_vapp_vm_nic_payload.zip/ansible/modules/vcd_vapp_vm_nic.py", line 154, in manage_states
  File "/tmp/ansible_vcd_vapp_vm_nic_payload_i55hukqe/ansible_vcd_vapp_vm_nic_payload.zip/ansible/modules/vcd_vapp_vm_nic.py", line 206, in add_nic
  File "/home/steffen/.local/lib/python3.7/site-packages/pyvcloud/vcd/vm.py", line 660, in add_nic
    vm_resource)
  File "/home/steffen/.local/lib/python3.7/site-packages/pyvcloud/vcd/client.py", line 1439, in post_linked_resource
    media_type, extra_headers=extra_headers)
  File "/home/steffen/.local/lib/python3.7/site-packages/pyvcloud/vcd/client.py", line 1422, in post_resource
    extra_headers=extra_headers)
  File "/home/steffen/.local/lib/python3.7/site-packages/pyvcloud/vcd/client.py", line 1169, in _do_request
    _objectify_response(response, objectify_results))
  File "/home/steffen/.local/lib/python3.7/site-packages/pyvcloud/vcd/client.py", line 1174, in _response_code_to_exception
    raise BadRequestException(sc, request_id, objectify_response)
pyvcloud.vcd.exceptions.BadRequestException: Status code: 400/BAD_REQUEST, [ ef427f97-1fc9-4e2b-ba7f-3a34477599f5 ] HTTP 400 Bad Request
 - cvc-elt.3.1: Attribute 'http://www.w3.org/2001/XMLSchema-instance,nil' must not appear on element 'NetworkAdapterType', because the {nillable} property of 'NetworkAdapterType' is false. (request id: ef427f97-1fc9-4e2b-ba7f-3a34477599f5)

**Comment by sgutermann** [comment]
Sorry for spamming this thread, but all I am trying to get working again is creating a vApp and a VM inside both connected up to two or more Org VDC Networks.

Worked a few months ago, now broken.

**Comment by mukultaneja** [comment]
@sgutermann, thanks for pointing out the documentation error. I am going to send an update for it. For the issue with `vcd_vapp_vm_nic`, you have to add `adapter_type`  in your playbook. Please refer to the wiki [here](https://github.com/vmware/ansible-module-vcloud-director/wiki/vCD-vApp-VM-Nic) and try adding it once.

**Comment by sgutermann** [comment]
@mukultaneja added the adapter type. New error still not working. Had to add by hand to a few machines in order to keep going.

The error ist telling me that the VDC Network can not be found and is "nil".

**Comment by mukultaneja** [comment]
could you please share your playbook and the error traceback?

**Comment by sgutermann** [comment]
@mukultaneja ok. Adding more than one VDC NEtwork to the vApp works (which ich what this issue is about) now. Just tested.
