### ISSUE TITLE
vcd_vapp_vm_nic cannot set NetworkAdapterType

### ISSUE THREAD

**Issue by carmineesposito73** [vmware/ansible-module-vcloud-director#63]
the function `add_nic` in `vcd_vapp_vm_nic` do not have parameter to set `NetworkAdapterType`.
issue #48 is related to `update_nic` instead.

**Comment by monadhiman** [comment]
Hi Folks,

Do we have any work around for this issue so that we  can update Network adapter type of a NIC on a VM either during NIC addition or updation.

Thank You in advance.

**Comment by carmineesposito73** [comment]
@monadhiman added the network adapter type in my repository, this feature has not been added to master repo

**Comment by monadhiman** [comment]
@carmineesposito73 Thanks for your reply on this. 
Could you please provide the link of your repository, As I can see only the master branch here.

Thank You.

**Comment by monadhiman** [comment]
@carmineesposito73 I am sorry, I got the path, I would test in my environment.
Thanks a lot for your help ! :)

**Comment by carmineesposito73** [comment]
@monadhiman, my repo is probably not updated with the master, I'm not using ansible for vcloud anymore

**Comment by monadhiman** [comment]
@carmineesposito73 sure, Thanks you.

**Comment by monadhiman** [comment]
@carmineesposito73 I tested vcd_vapp_vm_nic module in my environment and it worked fine with the other master files. Thank you.

@vmware This feature could be added the master branch as this is one of the basic requirements needed for windows VM build. In case of windows VM build it takes, E1000 adapter by default rather than vmxnet3. As tested vcd_vapp_vm_nic module from @carmineesposito73 repository, it works as expected.

Thank You.

**Comment by mukultaneja** [comment]
@monadhiman please confirm if the current module fits with your requirement.
