### ISSUE TITLE
vcd_vapp_vm_nic exception "no such child"

### ISSUE THREAD

**Issue by tomyerex** [vmware/ansible-module-vcloud-director#87]
Attempting to create a vApp VM NIC (vcd_vapp_vm_nic) and the following error occurs:

ansible_vcd_vapp_vm_nic_payload_7yiefu8a/ansible_vcd_vapp_vm_nic_payload.zip/ansible/module_utils/basic.py\", line 401, in _remove_values_conditions\nTypeError: Value of unknown type: <class 'AttributeError'>, **no such child: {http://www.vmware.com/vcloud/v1.5}NetworkConnection\n", "module_stdout": "", "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error", "rc": 1}**

Saw a similar error reported in issue "vcd_vapp_vm networking #32". Tried the code from that solution and the error persists. Tried with api 29.0 through 31.0.

**Comment by tomyerex** [comment]
During my own work, I found that if the VM already has a NIC defined, the same code will add another NIC without any error. The error only happens when the VM has no NICs at all.

**Comment by tomyerex** [comment]
I've been reading about the NIC and learned there might be something called a primary NIC in vCloud Director, which might be part of the problem here.

**Comment by rmharwood** [comment]
The problem here: when there is no NIC defined, the NetworkConnectionSection as returned by VDC contains no NetworkConnection objects: https://www.vmware.com/support/vcd/doc/rest-api-doc-1.5-html/types/NetworkConnectionSectionType.html

This piece of code is the culprit:
https://github.com/vmware/ansible-module-vcloud-director/blob/476c369134a567aa6fb9edcdd8fb93296e99fa35/modules/vcd_vapp_vm_nic.py#L230

This fails because there is no existing NetworkConnection element to add to.

The better approach would be how pyvcloud handles this, by inserting a new element:
https://github.com/vmware/pyvcloud/blob/614b137dd71679bda33a817308e44738f18d87bd/pyvcloud/vcd/vm.py#L512

In fact I am left wondering why the ansible module cannot just call this pyvcloud method, which was introduced in February 2019.

**Comment by monadhiman** [comment]
Hi All,

Is there any solution of this error? Thanks for giving suggestions.

Thank You.

**Comment by monadhiman** [comment]
> 
> 
> The problem here: when there is no NIC defined, the NetworkConnectionSection as returned by VDC contains no NetworkConnection objects: https://www.vmware.com/support/vcd/doc/rest-api-doc-1.5-html/types/NetworkConnectionSectionType.html
> 
> This piece of code is the culprit:
> 
> https://github.com/vmware/ansible-module-vcloud-director/blob/476c369134a567aa6fb9edcdd8fb93296e99fa35/modules/vcd_vapp_vm_nic.py#L230
> 
> This fails because there is no existing NetworkConnection element to add to.
> 
> The better approach would be how pyvcloud handles this, by inserting a new element:
> https://github.com/vmware/pyvcloud/blob/614b137dd71679bda33a817308e44738f18d87bd/pyvcloud/vcd/vm.py#L512
> 
> In fact I am left wondering why the ansible module cannot just call this pyvcloud method, which was introduced in February 2019.

Hi , So what could be the way out for this.?

**Comment by rmharwood** [comment]
My team and I have coded a fix for this, but as it involves fundamental changes to how vcd_vapp_vm_nic (and possibly other modules) works, we are not ready to publish at this time. In the mean time, the only workaround at present is to build from a template that has a NIC in it alredy.

**Comment by mukultaneja** [comment]
@rmharwood, @monadhiman, Apologies for having a late patch to address this issue. I hope this patch will help to resolve issues working with VM NICs.
